
use algotradingDB;
drop table if exists outside_pool_record;
create table outside_pool_record (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TRADINGID INT NOT NULL,
    STOCKID INT, 
    TIME DATETIME, 
    BUYSELL INT, 
    ISSYNC BOOL,
    TRADINGTYPE INT,
    EXPECTAMOUNT INT, 
    EXPECTPRICE DOUBLE,
    ISSUCCESS BOOL, 
    SUCCAMOUNT INT,
    SUCCMONEY DOUBLE,
    SUCCPRICE DOUBLE
);
drop table if exists client_orders;
create table client_orders(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    STOCKID INT, 
    STARTTIME DATETIME,
    ENDTIME DATETIME, 
    STOCKAMOUNT INT, 
    BUYSELL INT, 
    ALGOCHOICE INT, 
    COMPLETEDAMOUNT INT, 
    STATUS INT,
    QUANTANALYSIS MEDIUMTEXT,
    PROCESSID INT, 
    UPDATETIME DATETIME,
    NEXTUPDATETIME DATETIME,
    UPDATEINTERVAL INT,
    TRADETIME DATETIME,
    TRADINGTYPE INT,
    TURNOVER DOUBLE,
    AVGPRICE DOUBLE);

