cd ../algo_trading/
python algoTradingUnitTest.py
python repoForATUnitTest.py
cd ../common/
python MarketDataUnittest.py
cd ../pool/
python poolFromSinaApiUnitTest.py
python tradingRecordSaverUnitTest.py 
cd ../quant_analysis/
python LinearVWAPQuantAnalysisUnitTest.py
python TWAPQuantAnalysisUnitTest.py
python VWAPQuantAnalysisUnitTest.py
python quantAnalysisBaseUnitTest.py
cd ..
